---
- hosts: node1
  become: yes
  remote_user: ansible
  tasks: 
    - name: create file 
      copy: content="Hello World" dest=/tmp/file1.txt 
      
    - name: Copy Remote-To-Remote (from serverA to serverB)
      synchronize: src=/tmp/file12.txt dest=/tmp/ mode=pull checksum=yes compress=yes

      delegate_to: node2
